<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260410144824 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE stock_outbound (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, amount DOUBLE PRECISION NOT NULL, unit VARCHAR(255) NOT NULL, free_text_product_name VARCHAR(255) DEFAULT NULL, product_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6EE003CC4584665A ON stock_outbound (product_id)');
        $this->addSql('ALTER TABLE stock_outbound ADD CONSTRAINT FK_6EE003CC4584665A FOREIGN KEY (product_id) REFERENCES product_information (id)');
        $this->addSql('ALTER TABLE stock_inbound ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE stock_inbound ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE stock_outbound DROP CONSTRAINT FK_6EE003CC4584665A');
        $this->addSql('DROP TABLE stock_outbound');
        $this->addSql('ALTER TABLE stock_inbound DROP created_at');
        $this->addSql('ALTER TABLE stock_inbound DROP updated_at');
    }
}
