<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260403201546 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE app_configuration (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, key VARCHAR(255) NOT NULL, value TEXT DEFAULT NULL, type VARCHAR(50) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CONFIG_KEY ON app_configuration (key)');
        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, email VARCHAR(180) NOT NULL, username VARCHAR(255) NOT NULL, is_active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E9E7927C74 ON app_user (email)');
        $this->addSql('CREATE TABLE generic_task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, assignee_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_680437B659EC7D60 ON generic_task (assignee_id)');
        $this->addSql('CREATE TABLE inventory_item_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, category_name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE inventory_stock_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, current_quantity INT NOT NULL, min_quantity INT NOT NULL, unit VARCHAR(50) NOT NULL, product_information_id INT NOT NULL, category_id INT DEFAULT NULL, preferred_supply_source_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_45EF28597D994F2D ON inventory_stock_item (product_information_id)');
        $this->addSql('CREATE INDEX IDX_45EF285912469DE2 ON inventory_stock_item (category_id)');
        $this->addSql('CREATE INDEX IDX_45EF2859A2519D17 ON inventory_stock_item (preferred_supply_source_id)');
        $this->addSql('CREATE TABLE product_brand (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BD0E82045E237E06 ON product_brand (name)');
        $this->addSql('CREATE TABLE product_information (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, code VARCHAR(255) NOT NULL, product_name VARCHAR(500) DEFAULT NULL, generic_name TEXT DEFAULT NULL, brand_owner VARCHAR(500) DEFAULT NULL, quantity VARCHAR(255) DEFAULT NULL, product_quantity VARCHAR(255) DEFAULT NULL, packaging TEXT DEFAULT NULL, categories TEXT DEFAULT NULL, categories_tags TEXT DEFAULT NULL, main_category VARCHAR(255) DEFAULT NULL, food_groups TEXT DEFAULT NULL, pnns_groups1 VARCHAR(255) DEFAULT NULL, pnns_groups2 VARCHAR(255) DEFAULT NULL, ingredients_text TEXT DEFAULT NULL, ingredients_tags TEXT DEFAULT NULL, ingredients_analysis_tags TEXT DEFAULT NULL, labels TEXT DEFAULT NULL, labels_tags TEXT DEFAULT NULL, allergens TEXT DEFAULT NULL, energy_kcal100g NUMERIC(10, 2) DEFAULT NULL, proteins100g NUMERIC(10, 2) DEFAULT NULL, fat100g NUMERIC(10, 2) DEFAULT NULL, carbohydrates100g NUMERIC(10, 2) DEFAULT NULL, fiber100g NUMERIC(10, 2) DEFAULT NULL, vitamin_b12100g NUMERIC(10, 6) DEFAULT NULL, iron100g NUMERIC(10, 6) DEFAULT NULL, calcium100g NUMERIC(10, 6) DEFAULT NULL, stores TEXT DEFAULT NULL, purchase_places TEXT DEFAULT NULL, countries VARCHAR(255) DEFAULT NULL, environmental_score_score INT DEFAULT NULL, environmental_score_grade VARCHAR(255) DEFAULT NULL, image_url TEXT DEFAULT NULL, brand_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8556869C44F5D008 ON product_information (brand_id)');
        $this->addSql('CREATE TABLE product_supply_source (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, price NUMERIC(10, 2) DEFAULT NULL, product_url TEXT DEFAULT NULL, is_preferred BOOLEAN NOT NULL, last_checked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, product_information_id INT NOT NULL, supply_source_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_54B8D4307D994F2D ON product_supply_source (product_information_id)');
        $this->addSql('CREATE INDEX IDX_54B8D430EC487FAD ON product_supply_source (supply_source_id)');
        $this->addSql('CREATE TABLE shopping_list (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, name VARCHAR(255) NOT NULL, shopping_list_collection_id INT DEFAULT NULL, added_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3DC1A4598C16B41E ON shopping_list (shopping_list_collection_id)');
        $this->addSql('CREATE INDEX IDX_3DC1A45955B127A4 ON shopping_list (added_by_id)');
        $this->addSql('CREATE TABLE shopping_list_collection (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D328DE77E3C61F9 ON shopping_list_collection (owner_id)');
        $this->addSql('CREATE TABLE shopping_list_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, acquired BOOLEAN NOT NULL, quantity INT NOT NULL, shopping_list_id INT NOT NULL, product_information_id INT NOT NULL, added_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_ED7DEE2523245BF9 ON shopping_list_entry (shopping_list_id)');
        $this->addSql('CREATE INDEX IDX_ED7DEE257D994F2D ON shopping_list_entry (product_information_id)');
        $this->addSql('CREATE INDEX IDX_ED7DEE2555B127A4 ON shopping_list_entry (added_by_id)');
        $this->addSql('CREATE TABLE supply_source (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, name VARCHAR(255) NOT NULL, notes TEXT DEFAULT NULL, is_active BOOLEAN NOT NULL, type VARCHAR(255) NOT NULL, website_url VARCHAR(500) DEFAULT NULL, logo_url VARCHAR(500) DEFAULT NULL, address VARCHAR(500) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, postal_code VARCHAR(20) DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, opening_hours TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE task_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, description VARCHAR(255) NOT NULL, sort_order INT NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, task_id INT NOT NULL, completed_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EC8586508DB60186 ON task_entry (task_id)');
        $this->addSql('CREATE INDEX IDX_EC85865085ECDE76 ON task_entry (completed_by_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE generic_task ADD CONSTRAINT FK_680437B659EC7D60 FOREIGN KEY (assignee_id) REFERENCES app_user (id)');
        $this->addSql('ALTER TABLE inventory_stock_item ADD CONSTRAINT FK_45EF28597D994F2D FOREIGN KEY (product_information_id) REFERENCES product_information (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_stock_item ADD CONSTRAINT FK_45EF285912469DE2 FOREIGN KEY (category_id) REFERENCES inventory_item_category (id)');
        $this->addSql('ALTER TABLE inventory_stock_item ADD CONSTRAINT FK_45EF2859A2519D17 FOREIGN KEY (preferred_supply_source_id) REFERENCES supply_source (id)');
        $this->addSql('ALTER TABLE product_information ADD CONSTRAINT FK_8556869C44F5D008 FOREIGN KEY (brand_id) REFERENCES product_brand (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_supply_source ADD CONSTRAINT FK_54B8D4307D994F2D FOREIGN KEY (product_information_id) REFERENCES product_information (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_supply_source ADD CONSTRAINT FK_54B8D430EC487FAD FOREIGN KEY (supply_source_id) REFERENCES supply_source (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shopping_list ADD CONSTRAINT FK_3DC1A4598C16B41E FOREIGN KEY (shopping_list_collection_id) REFERENCES shopping_list_collection (id)');
        $this->addSql('ALTER TABLE shopping_list ADD CONSTRAINT FK_3DC1A45955B127A4 FOREIGN KEY (added_by_id) REFERENCES app_user (id)');
        $this->addSql('ALTER TABLE shopping_list_collection ADD CONSTRAINT FK_8D328DE77E3C61F9 FOREIGN KEY (owner_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shopping_list_entry ADD CONSTRAINT FK_ED7DEE2523245BF9 FOREIGN KEY (shopping_list_id) REFERENCES shopping_list (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shopping_list_entry ADD CONSTRAINT FK_ED7DEE257D994F2D FOREIGN KEY (product_information_id) REFERENCES product_information (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shopping_list_entry ADD CONSTRAINT FK_ED7DEE2555B127A4 FOREIGN KEY (added_by_id) REFERENCES app_user (id)');
        $this->addSql('ALTER TABLE task_entry ADD CONSTRAINT FK_EC8586508DB60186 FOREIGN KEY (task_id) REFERENCES generic_task (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task_entry ADD CONSTRAINT FK_EC85865085ECDE76 FOREIGN KEY (completed_by_id) REFERENCES app_user (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE generic_task DROP CONSTRAINT FK_680437B659EC7D60');
        $this->addSql('ALTER TABLE inventory_stock_item DROP CONSTRAINT FK_45EF28597D994F2D');
        $this->addSql('ALTER TABLE inventory_stock_item DROP CONSTRAINT FK_45EF285912469DE2');
        $this->addSql('ALTER TABLE inventory_stock_item DROP CONSTRAINT FK_45EF2859A2519D17');
        $this->addSql('ALTER TABLE product_information DROP CONSTRAINT FK_8556869C44F5D008');
        $this->addSql('ALTER TABLE product_supply_source DROP CONSTRAINT FK_54B8D4307D994F2D');
        $this->addSql('ALTER TABLE product_supply_source DROP CONSTRAINT FK_54B8D430EC487FAD');
        $this->addSql('ALTER TABLE shopping_list DROP CONSTRAINT FK_3DC1A4598C16B41E');
        $this->addSql('ALTER TABLE shopping_list DROP CONSTRAINT FK_3DC1A45955B127A4');
        $this->addSql('ALTER TABLE shopping_list_collection DROP CONSTRAINT FK_8D328DE77E3C61F9');
        $this->addSql('ALTER TABLE shopping_list_entry DROP CONSTRAINT FK_ED7DEE2523245BF9');
        $this->addSql('ALTER TABLE shopping_list_entry DROP CONSTRAINT FK_ED7DEE257D994F2D');
        $this->addSql('ALTER TABLE shopping_list_entry DROP CONSTRAINT FK_ED7DEE2555B127A4');
        $this->addSql('ALTER TABLE task_entry DROP CONSTRAINT FK_EC8586508DB60186');
        $this->addSql('ALTER TABLE task_entry DROP CONSTRAINT FK_EC85865085ECDE76');
        $this->addSql('DROP TABLE app_configuration');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('DROP TABLE generic_task');
        $this->addSql('DROP TABLE inventory_item_category');
        $this->addSql('DROP TABLE inventory_stock_item');
        $this->addSql('DROP TABLE product_brand');
        $this->addSql('DROP TABLE product_information');
        $this->addSql('DROP TABLE product_supply_source');
        $this->addSql('DROP TABLE shopping_list');
        $this->addSql('DROP TABLE shopping_list_collection');
        $this->addSql('DROP TABLE shopping_list_entry');
        $this->addSql('DROP TABLE supply_source');
        $this->addSql('DROP TABLE task_entry');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
