<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260410122755 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE stock_inbound (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount DOUBLE PRECISION NOT NULL, unit VARCHAR(255) NOT NULL, free_text_product_name VARCHAR(255) DEFAULT NULL, product_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CB36226A4584665A ON stock_inbound (product_id)');
        $this->addSql('ALTER TABLE stock_inbound ADD CONSTRAINT FK_CB36226A4584665A FOREIGN KEY (product_id) REFERENCES product_information (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE stock_inbound DROP CONSTRAINT FK_CB36226A4584665A');
        $this->addSql('DROP TABLE stock_inbound');
    }
}
