<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260124185518 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE app_configuration (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, key VARCHAR(255) NOT NULL, value TEXT DEFAULT NULL, type VARCHAR(50) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CONFIG_KEY ON app_configuration (key)');
        $this->addSql('CREATE TABLE product_brand (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BD0E82045E237E06 ON product_brand (name)');
        $this->addSql('CREATE TABLE product_information (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, brand_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8556869C44F5D008 ON product_information (brand_id)');
        $this->addSql('CREATE TABLE shopping_list (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, name VARCHAR(255) NOT NULL, shopping_list_collection_id INT DEFAULT NULL, added_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3DC1A4598C16B41E ON shopping_list (shopping_list_collection_id)');
        $this->addSql('CREATE INDEX IDX_3DC1A45955B127A4 ON shopping_list (added_by_id)');
        $this->addSql('CREATE TABLE shopping_list_collection (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D328DE77E3C61F9 ON shopping_list_collection (owner_id)');
        $this->addSql('CREATE TABLE shopping_list_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, acquired BOOLEAN NOT NULL, quantity INT NOT NULL, shopping_list_id INT NOT NULL, product_information_id INT NOT NULL, added_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_ED7DEE2523245BF9 ON shopping_list_entry (shopping_list_id)');
        $this->addSql('CREATE INDEX IDX_ED7DEE257D994F2D ON shopping_list_entry (product_information_id)');
        $this->addSql('CREATE INDEX IDX_ED7DEE2555B127A4 ON shopping_list_entry (added_by_id)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, email VARCHAR(180) NOT NULL, username VARCHAR(255) NOT NULL, is_active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE product_information ADD CONSTRAINT FK_8556869C44F5D008 FOREIGN KEY (brand_id) REFERENCES product_brand (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shopping_list ADD CONSTRAINT FK_3DC1A4598C16B41E FOREIGN KEY (shopping_list_collection_id) REFERENCES shopping_list_collection (id)');
        $this->addSql('ALTER TABLE shopping_list ADD CONSTRAINT FK_3DC1A45955B127A4 FOREIGN KEY (added_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE shopping_list_collection ADD CONSTRAINT FK_8D328DE77E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shopping_list_entry ADD CONSTRAINT FK_ED7DEE2523245BF9 FOREIGN KEY (shopping_list_id) REFERENCES shopping_list (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shopping_list_entry ADD CONSTRAINT FK_ED7DEE257D994F2D FOREIGN KEY (product_information_id) REFERENCES product_information (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shopping_list_entry ADD CONSTRAINT FK_ED7DEE2555B127A4 FOREIGN KEY (added_by_id) REFERENCES users (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE product_information DROP CONSTRAINT FK_8556869C44F5D008');
        $this->addSql('ALTER TABLE shopping_list DROP CONSTRAINT FK_3DC1A4598C16B41E');
        $this->addSql('ALTER TABLE shopping_list DROP CONSTRAINT FK_3DC1A45955B127A4');
        $this->addSql('ALTER TABLE shopping_list_collection DROP CONSTRAINT FK_8D328DE77E3C61F9');
        $this->addSql('ALTER TABLE shopping_list_entry DROP CONSTRAINT FK_ED7DEE2523245BF9');
        $this->addSql('ALTER TABLE shopping_list_entry DROP CONSTRAINT FK_ED7DEE257D994F2D');
        $this->addSql('ALTER TABLE shopping_list_entry DROP CONSTRAINT FK_ED7DEE2555B127A4');
        $this->addSql('DROP TABLE app_configuration');
        $this->addSql('DROP TABLE product_brand');
        $this->addSql('DROP TABLE product_information');
        $this->addSql('DROP TABLE shopping_list');
        $this->addSql('DROP TABLE shopping_list_collection');
        $this->addSql('DROP TABLE shopping_list_entry');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
