<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260116173623 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE shopping_list (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, name VARCHAR(255) NOT NULL, shopping_list_collection_id INT DEFAULT NULL, added_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3DC1A4598C16B41E ON shopping_list (shopping_list_collection_id)');
        $this->addSql('CREATE INDEX IDX_3DC1A45955B127A4 ON shopping_list (added_by_id)');
        $this->addSql('CREATE TABLE shopping_list_collection (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, name VARCHAR(255) NOT NULL, owner VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE shopping_list_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, shopping_list_id INT NOT NULL, product_information_id INT NOT NULL, added_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_ED7DEE2523245BF9 ON shopping_list_entry (shopping_list_id)');
        $this->addSql('CREATE INDEX IDX_ED7DEE257D994F2D ON shopping_list_entry (product_information_id)');
        $this->addSql('CREATE INDEX IDX_ED7DEE2555B127A4 ON shopping_list_entry (added_by_id)');
        $this->addSql('ALTER TABLE shopping_list ADD CONSTRAINT FK_3DC1A4598C16B41E FOREIGN KEY (shopping_list_collection_id) REFERENCES shopping_list_collection (id)');
        $this->addSql('ALTER TABLE shopping_list ADD CONSTRAINT FK_3DC1A45955B127A4 FOREIGN KEY (added_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE shopping_list_entry ADD CONSTRAINT FK_ED7DEE2523245BF9 FOREIGN KEY (shopping_list_id) REFERENCES shopping_list (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shopping_list_entry ADD CONSTRAINT FK_ED7DEE257D994F2D FOREIGN KEY (product_information_id) REFERENCES product_information (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shopping_list_entry ADD CONSTRAINT FK_ED7DEE2555B127A4 FOREIGN KEY (added_by_id) REFERENCES users (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE shopping_list DROP CONSTRAINT FK_3DC1A4598C16B41E');
        $this->addSql('ALTER TABLE shopping_list DROP CONSTRAINT FK_3DC1A45955B127A4');
        $this->addSql('ALTER TABLE shopping_list_entry DROP CONSTRAINT FK_ED7DEE2523245BF9');
        $this->addSql('ALTER TABLE shopping_list_entry DROP CONSTRAINT FK_ED7DEE257D994F2D');
        $this->addSql('ALTER TABLE shopping_list_entry DROP CONSTRAINT FK_ED7DEE2555B127A4');
        $this->addSql('DROP TABLE shopping_list');
        $this->addSql('DROP TABLE shopping_list_collection');
        $this->addSql('DROP TABLE shopping_list_entry');
    }
}
